version: "3.8"

networks:
  rca-net:
    driver: bridge

volumes:
  tempo-data:
  prometheus-data:
  grafana-data:
  ollama-data:

services:

  tempo:
    image: grafana/tempo:2.6.1
    container_name: tempo
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./infra/tempo.yml:/etc/tempo.yml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"   # HTTP API — el agente consulta trazas acá
      - "4317:4317"   # gRPC — recibe spans del open telemetry collector (OTel) Collector
    networks:
      - rca-net

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - rca-net

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - tempo
      - prometheus
    networks:
      - rca-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./infra/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4318:4318"   # HTTP — los servicios Kotlin mandan spans acá
    depends_on:
      - tempo
      - prometheus
    networks:
      - rca-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - rca-net